---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)

rm(list=ls())
#plot the positions

load("./data/expeditionclean.rda")
load("./data/marks.Rdata")
load("./data/positions_wcorr.Rdata")
load("./data/results.Rdata")

pos <- left_join(pos, results)


```



```{r}

#get states shape files
mi <- map_data("state") %>% filter(region=="michigan")

#get zube's position from Yellowbrick
zub <- pos %>% filter(boat=="Zubenelgenubi")

#plot the positions
ggplot()+
  geom_polygon(data=mi, aes(long, lat, group=group)) + 
  coord_map("mercator", xlim=c(-85, -82), ylim=c(42.8, 46)) + 
  geom_point(data=exp, aes(x=Lon, y=Lat), color="blue")+
  geom_path(data=zub, aes(x=lon, y=lat), color="red")


```

```{r}
classo <- pos %>% filter(class=="Class O Class") %>% filter(place != "RET")


ggplot()+
  geom_polygon(data=mi, aes(long, lat, group=group)) + 
  coord_map("mercator", xlim=c(-85, -82), ylim=c(42.8, 46))+
  geom_path(data=classo, aes(x=lon, y=lat, color=boat))+
  geom_path(data=zub, aes(x=lon, lat), color="red")

```

Look at seperation between boats
```{r}
ggplot()+
  geom_path(data=classo, aes(x=time, y=dmg, color=boat, linetype=boat)) + 
  geom_path(data=zub, aes(x=time, y=dmg))+
  geom_hline(data=marks, aes(yintercept=dmg))+
  geom_text(data=marks, aes(x=min(classo$time), y=dmg, label=mark), size = 2, nudge_y = 2)
```

looking at our speed vs. the 
```{r}

exp <- exp %>% filter(Sog < 10)

ggplot()+geom_point(data=exp, aes(x=time, y=Sog))+geom_point(data=zub, aes(x=time, y=SOG), color="red")


```

How good is the SOG estimate from Yellowbrick

```{r}

#try to join the two frames by nearest time
library(lubridate)

zub$time <- round_date(zub$time, unit="second")
exp$time <- round_date(exp$time, unit="second")

class(zub$time) == class(exp$time)

joined <- full_join(zub, exp) %>% arrange(time)

ggplot()+ geom_point(data=joined, aes(x=Sog, y=SOG)) + geom_abline(aes(slope=1, intercept=0)) + ggtitle("SOG from Yellowbrick vs. GPS Sog") + scale_x_continuous(name="GPS SOG") + scale_y_continuous(name="Yellowbrick SOG")

```

#look at measured BSP (from Raymarine) vs. SOG
```{r}
ggplot(joined, aes(x=Sog, y=Bsp)) + 
  geom_point(alpha=0.1, aes(color="Garmin GPS")) + 
  geom_abline(aes(slope=1, intercept=0, color="1:1 ratio"), color="Black", linetype=2)+
  geom_point(aes(x=SOG, y=Bsp, color="Yellowbrick")) + 
  geom_smooth(method="lm") + 
  scale_y_continuous(name = "Boat Speed (BPS) through the water", breaks=seq(0,8, by=1)) +
  scale_x_continuous(name = "Speed over Group (SOG) from GPS", breaks=seq(0,8, by=1))+
    guides(color = guide_legend("GPS Type"))+scale_color_brewer(palette = "Dark2")+
  ggtitle("Boat Speed through the water (Paddlewheel) vs. Speed over Group (GPS)")
```

```{r}

ggplot(joined[joined$Bsp > 2, ]) + geom_histogram(aes(x=Bsp), binwidth = 0.05) + scale_x_continuous(breaks = seq(0, 10, by=0.2))

ggplot(joined[joined$Bsp < 4, ]) + geom_histogram(aes(x=Bsp), binwidth = 0.05)
```




