---
title: "R Notebook"
output: html_notebook
---


```{r}

btm <- seq(0, 360, by=30)

twd <- runif(length(btm), min = 0, max=360)

dmark <- getDiffMarkWind(btm, twd)

tws <- runif(length(dmark), min = 4, max= 12)


getOptVMC <- function(diffwind, tws, pol.model){
  #variable = offmark distance between wind and mark
  
  twa <- seq(0,180, by=1)
  
  #test angles off the mark
  offmark <- twa - diffwind
  
  #get the polar curve
  v <- getOptV(twa, tws, pol.model)
  
  #vmc 
  vmc <- v*cos(offmark*(pi/180))
  
  vmcMax <- max(vmc)
  
  opt <- data.frame(diffwind, tws, twa, offmark, v, vmc)
  
  return(opt[which(vmcMax == vmc), ])
         
}


test <- mapply(FUN = getOptVMC, dmark, tws, MoreArgs = list(pol.model = pol.model), SIMPLIFY = FALSE)

test

```



```{r}
x <- 1

btm <- runif(n=x, min = 0, max=360)
twd <- runif(n=x, min = 0, max=360)
tws <- runif(n=x, min = 3, max=20)



opt <- unlist(mapply(FUN = optvmc, btm, twd, tws, MoreArgs = list(pol.model), SIMPLIFY = FALSE))

twa <- seq(0, 180, by=1)

toMark <- convBearing(twd) - convBearing(btm) 

twa_port <- seq(180, 360, by=1)

v <- getOptV(btw = twa, vtw = tws, pol.model)


ggplot()+
  geom_path(aes(x=convBearingBack(twa_port+twd), y=rev(v)), color="red")+
  geom_path(aes(x=twa+twd, y=getOptV(twa, tws, pol.model)), color="green")+
  #geom_point(aes(x=twa_m, y=getOptV(twa, tws, pol.model)), color="red")+
  coord_polar()+
  scale_x_continuous(limits=c(0,360), breaks=seq(0, 360, by=30))+
  geom_vline(xintercept = twd)+
  geom_vline(xintercept = convBearingBack(opt["opt_twa"]), color="magenta")+
  geom_vline(xintercept = convBearingBack(toMark), color="blue")




```


```{r}
x <- 1

twd <- runif(n=x, min = -180, max=180)

convBearing <- function(bearing){
  ifelse(bearing>180, bearing-360, bearing)
}


#normBear (any negative or larger than 360, conver to bearing)

normbear <- function(x){
  x %% 360
}
                     
print(twd)
normbear(twd)

ggplot()+
  geom_vline(xintercept = twd)+
  geom_vline(xintercept = normbear(twd), color="blue")+
  scale_x_continuous(limits=c(0,360), breaks=seq(0, 360, by=30))+

  coord_polar()
  



```

```{r}
getOptV <- function(btw, vtw, pol.model){
  #returns Optimal Velocity at a given Bearing to Wind (BTW) and Wind Speed (VTW)
  btw <- normbear(btw)
  
  btw <- convBearing(btw)

  btw <- abs(btw)
    
  #ensure that the length of both btw and vtw are the same...
  inputvectors <- matchLength(btw, vtw)
  btw <- inputvectors[[1]]
  vtw <- inputvectors[[2]]
  
  #output the optimum Velocity for a given BTW and wind speed. 
  v <- bilinear(x=pol.model$twa, y=pol.model$tws, z=pol.model$pol.matrix, x0=btw, y0=vtw)
  
  return(v$z)
  
}


```




```{r}

x <- 1

btm <- runif(n=x, min = 0, max=360)
twd <- runif(n=x, min = 0, max=360)
tws <- runif(n=x, min = 3, max=20)

twa_s <- seq(0,180, by=2)
twa_p <- normbear(seq(0,-180, by=-2))

v_s <- getOptV(twa_s, vtw=tws, pol.model)
v_p <- getOptV(twa_p, vtw=tws, pol.model)


opt <- unlist(mapply(FUN = optvmc, btm, twd, tws, MoreArgs = list(pol.model), SIMPLIFY = FALSE))

opt_bear <- opt["opt_bear"]

ggplot()+ 
  geom_path(aes(x=normbear(twa_s+twd), y=v_s, group="group"), color="green")+
  geom_path(aes(x=normbear(twa_p+twd), y=v_p, group="group"), color="red")+
  coord_polar()+
  scale_x_continuous(limits=c(0,360), breaks=seq(0, 360, by=30))+
  geom_vline(xintercept=twd)+
  #geom_vline(xintercept = normbear(opt["opt_bear"]), color="magenta")+
  geom_segment(aes(x=opt_bear, xend=opt_bear, y=0, yend=opt["opt_bsp"]), color="magenta")+
  geom_vline(xintercept = normbear(btm), color="blue")
  
  
print(opt)

```










